- lib/av_client.ts
- lib/av_client/authenticate_with_codes.ts
- lib/av_client/benaloh_challenge.ts
- lib/av_client/encrypt_votes.ts
- lib/av_client/generate_key_pair.ts
- lib/av_client/register_voter.ts
- lib/av_client/sign.ts
- lib/av_client/submit_votes.ts
- lib/av_client/types.ts
* Remove/reduce duplicate type definitions
* Fix naming
* Clean import paths
Verified using us-ionic-demo e2e test suite
> A couple of refactorings

- README.md
- test/authenticate_with_codes.test.ts
- test/get_authorization_method.test.ts
- test/request_access_code.test.ts
* Add missing type annotation
* (unrelated) Add how-to-install the package in README.md
Fixes #DEV-114
> Ensure tests use statically typed AVClient

- test/calls_out_of_order.test.ts
- test/recorder.test.ts
Removed 2 skipped tests, explained when recorder test should be enabled.
> Cleanup of skipped tests

- package-lock.json
- package.json
Solving https://github.com/aion-dk/js-client/security/dependabot/package-lock.json/ansi-regex/open
> Bumped ansi-regex to a non-vulnerable version for CVE-2021-3807

- lib/av_client/authenticate_with_codes.ts
- lib/av_client/connectors/bulletin_board.ts
- lib/av_client/election_config.ts
- lib/av_client/encrypt_votes.ts
> Fix 27 linter warnings (missing types)

- .gitignore
- .npmignore
This PR reduces the size of the package by removing a bunch of unnecessary artifacts from the package.
> Remove unnecessary artifacts from the npm package

- lib/util/nist_converter.ts
- lib/util/nist_types.ts
- test/cvrs/sample2.xml
- test/nist_converter.test.ts
Why comment a PR, when one can just make another PR on top of it.
> Fixed extracting correct snapshot

- lib/av_client.ts
- lib/av_client/types.ts
- lib/util/nist_converter.ts
- lib/util/nist_types.ts
- package-lock.json
- package.json
- test/cvrs/jetsons_bedrock-precinct2_cvr.xml
- test/cvrs/no_contest_selection.xml
- test/cvrs/no_contests.xml
- test/cvrs/sample1.xml
- test/cvrs/sample2.xml
- test/nist_converter.test.ts
Utility module for converting from NIST 1500-103 CVRs to AV CVRs.
> Add NIST 1500-103 converter

- lib/util/nist_converter.ts
- test/nist_converter.test.ts
Handling of malformed NIST CVRs.
> Add tests for missing and malformed NIST CVRs

- .github/workflows/package.yml
- .github/workflows/tests.yml
- docs/index.html
- lib/av_client.ts
- lib/av_client/connectors/bulletin_board.ts
- lib/av_client/encrypt_votes.ts
- lib/av_client/sign.ts
- lib/av_client/submit_votes.ts
- lib/util/nist_converter.ts
Hard to believe... but this PR takes # of linter errors to zero.
Also GH action workflow is now running the linter step.
> Fix ALL linter errors

- package-lock.json
- package.json
> Bump to version 0.1.12

- CHANGELOG.md
- package-lock.json
- package.json
> Bump JS-client to version 0.1.13

- test/bulletin_board.test.ts
- test/calls_out_of_order.test.ts
- test/construct_ballot_cryptograms.test.ts
- test/election_configuration_validation.test.ts
- test/readme_example.test.ts
- test/readme_example_helper.ts
- test/request_access_code.test.ts
- test/submit_ballot_cryptograms.test.ts
- test/validate_access_code.test.ts
- test/walkthrough.test.ts
This is needed to make the CORS policies implementable.
> Update all AVX URLs to new proposed /mobile-api prefix

- lib/av_client.ts
- lib/av_client/connectors/bulletin_board.ts
- lib/av_client/register_voter.ts
- lib/av_client/submit_votes.ts
- test/bulletin_board.test.ts
I have run the e2e tests with the us-ionic-app and everything seems to be working
> replaced registration and publicKey token with authToken

- lib/av_client/errors.ts
- lib/av_client/flatten_options.ts
- lib/av_client/types.ts
- lib/av_client/validate_selections.ts
- test/cvr_validation.test.ts
- test/eligibility_check.test.ts
- test/validate_selections.test.ts
This PR introduces:
- Adds reference to BallotConfig (alignment with DBB)
- BallotSelection type to contain a selection for an entire ballot
- Validator functions that tests a BallotSelection or ContestSelection against the ContestConfig (MarkingType)
> Vote encoding - part 4 (Vote validation)

- lib/av_client.ts
- lib/av_client/types.ts
- test/replies/benaloh_flow/http_dbb_3003/get__us_configuration.json
- test/replies/otp_flow/get_us_configuration.json
[DEV-1397](https://github.com/aion-dk/dbb/pull/102)
> Update js-client to support DEV-1397

- lib/av_client/types.ts
- lib/av_client/validate_selections.ts
- test/construct_contest_envelopes.test.ts
- test/decrypt_contest_selections.test.ts
- test/encoding/byte_encoding.test.ts
- test/encrypt_contest_selections.test.ts
- test/replies/benaloh_flow/http_dbb_3003/get__us_configuration.json
- test/replies/otp_flow/get_us_configuration.json
- test/validate_selections.test.ts
- test/verifier/readable_contest_selections.test.ts
Also improved tests and added new ones
> Make blank validation based on new config in marking type

- CHANGELOG.md
- package.json
> Updated version and changelog for new release v1.1.5

- lib/av_verifier.ts
- test/verifier/readable_contest_selections.test.ts
This fixes a bug where write-ins aren't shown in VMB.
> Don't throw write-ins away

- lib/av_client.ts
- package.json
- yarn.lock
The main flow should not be broken if we encounter an error when sending the tracking code in an email
> Catch email error

- lib/av_client.ts
- package.json
Made identityToken assignable and have the flow be possible without explicit authorizationMode == "proof-of-identity"
> [TECH-2517] Proper session transfer from Logins to Electa
