- test/replies/avx_error.invalid_4.json
- test/replies/avx_error.invalid_5.json
- test/replies/avx_error.invalid_6.json
- test/replies/avx_error.invalid_7.json
A global search of "avx_error.invalid" shows that only avx_error.invalid_2.json & avx_error.invalid_3.json are used.
> Removed unused previously recorded replies

- .nycrc
Docs don't contain code, and sjcl.js is presumably [passing tests](https://travis-ci.org/github/bitwiseshiftleft/sjcl).
> Exclude docs and sjcl.js from coverage reports

- .github/workflows/package.yml
- CHANGELOG.md
- package.json
For some reason the aion_crypto.js + sjcl.js was missing in the published package.
This fixes that problem, as well as introduces automatic publishing when a release is created in Github.
> Fix missing js files in published package

- CHANGELOG.md
- package.json
Adding package metadata will show links on https://www.npmjs.com/package/@aion-dk/js-client for where source code and documentation is located.
Wrap up a release where IAVClient interface is correctly exported.
> Add package metadata for npmjs.com

- .github/workflows/package.yml
This commit changes publishing to npmjs.org instead of Github's
registry.
Last two releases were published manually, this change automates the publishing step.
> Publish to npmjs.org when a Github release is created

- test/walkthrough.test.ts
For a full integration test we should use BABE as the voter registry. This means we have to update the credentials to something that exists in their database.
Because we use a static value as the voter credential we have to reset the AVX database after each integration test, since we only allow one vote per voter.
The timeout for testing the voting flow have been increased because it would often take longer than the default timeout of 2 seconds. 
Typical run of integration test
> Updated walkthrough test with test credential for BABE

- lib/util/uniformer.ts
- test/uniformer.test.ts
Adding a uniformer which can ensure that hashing of complex objects always produce the same result, by deterministic serialization.
> Add uniformer

- .github/workflows/docs.yml
- .github/workflows/tests.yml
To safe-guard against supply chain vulnerabilities, this commit pins our
usage of ad-m/github-push-action (Github Action) to a specific commit
id. This is especially important since this action receives a secret
token.
> Pin 3rd party version of github-push-action

- package-lock.json
- package.json
This fixes dependabot warning for https://github.com/advisories/GHSA-5v2h-r2cx-5xgj
* Updating marked package (used by typedoc) to 4.0.10. Fixes regex security issue.
* Updating axios to 0.25.0
> Update axios, typedoc, etc package

- lib/av_client/aion_crypto.js
- lib/av_client/encrypt_votes.ts
- lib/av_client/generate_key_pair.ts
- lib/av_client/register_voter.ts
- lib/av_client/sign.ts
- test/submit_ballot_cryptograms.test.ts
I propose that we clean up how functions (and which) are exported from aion_crypto.
This is done to streamline how we import modules/libraries (i.e. avoid using `const .. = require()`).
* Disabled export of unused functions. Would like a discussion on what
should happen to these (required?, deprecated? remove them?).
> Change how functions are exported from aion crypto

- package-lock.json
Outdated transitive dependency 'nanoid' had a vulnerability prior to version
3.1.31.
Also updated other outdated libs.
> Fix dependabot alert

- lib/av_client/aion_crypto.js
- lib/av_client/crypto/bignum.ts
- lib/av_client/crypto/bitarray.ts
- lib/av_client/crypto/pedersen_commitment.ts
- lib/av_client/crypto/point.ts
- lib/av_client/crypto/util.ts
- package.json
- test/crypto/commitment.test.ts
Adds generation and verification of encryption commitments.
As part of the discussion on how to turn aion_crypto into a tested, standalone, high quality library this PRs proposes to start splitting things into smaller separate modules, and using static typing (typescript).
As the underlying crypto implementation (SJCL) uses untyped JS classes, this PR introduces typed wrapper classes for Point and Bignum.
* Written in typescript, and using a typescript wrapper of aion_crypto lib.
* Added unit tests for generator & verifier functions.
* Validated against commitment generator implementation in the backend
> Generate and verify commitments

- lib/av_client/crypto/vote_converter.ts
- test/readme_example.test.ts
- test/submit_ballot_cryptograms.test.ts
- test/walkthrough.test.ts
Removes encoding types that are no longer used.
The 3 broken tests are also broken on the base branch. This is caused by some tests being deprecated and need to be replaced/re-written.
> Deprecated encoding types

- lib/av_client/encoding/byte_encoding.ts
- lib/av_client/types.ts
- test/encoding/byte_encoding.test.ts
This PR introduces:
- High level encoder from ContestSelection to ByteArray
- ContestSelection and OptionSelection types (will in time replace CastVoteRecord)
The code is only mapped to tests at the moment, but a later pull request will tie it together with the other encoding parts
> Vote encoding - part 3 (Adding byte_encoding and ContestSelection types)

- lib/util/uniformer.ts
- test/uniformer.test.ts
We need to sort the same in all uniformer implementations. To align with DBB we order strings by the utf8 bytes they are made of
> Align uniformer sorting with DBB

- .github/workflows/tests.yml
It is not working together with new branch protections where no commits must be done on main
> Delete coverage badge generation from github CI

- .github/workflows/package.yml
- package.json
The action as a whole failed, but the package was published. The error was:
The action that failed:
https://github.com/aion-dk/js-client/runs/8250137822?check_suite_focus=true#step:11:4
edit:
The package was not correctly published, and appears to be missing files. [This](https://stackoverflow.com/questions/65922489/how-is-npm-publish-different-from-yarn-publish) might be the answer, also included here
> Fixes package publish action maybe?

- lib/av_client/encoding/byte_encoding.ts
- lib/av_client/flatten_options.ts
- lib/av_client/option_finder.ts
- lib/av_client/types.ts
- lib/av_client/validate_selections.ts
- test/benaloh_flow.test.ts
- test/construct_contest_envelopes.test.ts
- test/decrypt_contest_selections.test.ts
- test/encoding/byte_encoding.test.ts
- test/encrypt_contest_selections.test.ts
- test/fixtures/latestConfig.ts
- test/validate_selections.test.ts
It is necessary to have correct typing on the JS-client because other applications are importing them. This also helps to have typing management centralized in one file when updating the format of the Config Items.
> Refactoring types

- .editorconfig
This standardizes our editors with the same settings as to how to treat common settings, like:
* Line endings;
* Blank spaces;
* Tabs vs Spaces;
* ...and more.
> Adding Global editor settings

- lib/av_client.ts
- package.json
- yarn.lock
Replaces 'jose' dependency with 'auth0/jwt-decode' to handle jwt decoding. 'jose' does not work with React Native.
> Replace 'jose' dependency with 'auth0/jwt-decode'

- lib/av_client.ts
- lib/av_client/connectors/voter_authorization_coordinator.ts
Working with changing locales was not a consideration for US, meaning the structure is not well suited for client side changes to the locale. 
Ideally the AVClient should be instantiated with a locale we can simply access, but it would also have to be updated if the outer UI changes locale...
> Add locale for sendReceipt
